export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_RESETED = 'REGISTER_RESETED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_RESETED = 'LOGIN_RESETED';
