export const FETCH_COMMENT_REQUESTED = 'FETCH_COMMENT_REQUESTED';
export const FETCH_COMMENT_SUCCEED = 'FETCH_COMMENT_SUCCEED';
export const FETCH_COMMENT_CLEAR = 'FETCH_COMMENT_CLEAR';
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED';

export const CREATE_COMMENT_REQUESTED = 'CREATE_COMMENT_REQUESTED';
export const CREATE_COMMENT_SUCCEED = 'CREATE_COMMENT_SUCCEED';
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';

export const CREATE_REPLY_COMMENT_REQUESTED = 'CREATE_REPLY_COMMENT_REQUESTED';
export const CREATE_REPLY_COMMENT_SUCCEED = 'CREATE_REPLY_COMMENT_SUCCEED';
export const CREATE_REPLY_COMMENT_FAILED = 'CREATE_REPLY_COMMENT_FAILED';
