export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
export const SORT_BY_POST_SUCCEED = 'SORT_BY_POST_SUCCEED';
export const FILTER_BY_POST_SUCCEED = 'FILTER_BY_POST_SUCCEED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';
export const FETCH_POST_RESETED = 'FETCH_POST_RESETED';

export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
export const LOAD_DATA = 'LOAD_DATA';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_VALUE = 'FILTER_BY_VALUE';

export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const CREATE_POST_SUCCEED = 'CREATE_POST_SUCCEED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_RESETED = 'CREATE_POST_RESETED';

export const SINGLE_POST_REQUESTED = 'SINGLE_POST_REQUESTED';
export const SINGLE_POST_SUCCEED = 'SINGLE_POST_SUCCEED';
export const SINGLE_POST_FAILED = 'SINGLE_POST_FAILED';
export const SINGLE_POST_RESETED = 'SINGLE_POST_RESETED';

export const EDIT_POST_REQUESTED = 'EDIT_POST_REQUESTED';
export const EDIT_POST_SUCCEED = 'EDIT_POST_SUCCEED';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';
export const EDIT_POST_RESETED = 'EDIT_POST_RESETED';

export const UPDATE_POST_REQUESTED = 'UPDATE_POST_REQUESTED';
export const UPDATE_POST_SUCCEED = 'UPDATE_POST_SUCCEED';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';
export const UPDATE_POST_RESETED = 'UPDATE_POST_RESETED';

export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED';
export const DELETE_POST_SUCCEED = 'DELETE_POST_SUCCEED';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';
export const DELETE_POST_RESETED = 'DELETE_POST_RESETED';
