export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const CREATE_POST_SUCCEED = 'CREATE_POST_SUCCEED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';

export const UPDATE_POST_REQUESTED = 'UPDATE_POST_REQUESTED';
export const UPDATE_POST_SUCCEED = 'UPDATE_POST_SUCCEED';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';

export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED';
export const DELETE_POST_SUCCEED = 'DELETE_POST_SUCCEED';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const DETAIL_POST_REQUESTED = 'DETAIL_POST_REQUESTED';
export const DETAIL_POST_SUCCEED = 'DETAIL_POST_SUCCEED';
export const DETAIL_POST_FAILED = 'DETAIL_POST_FAILED';