export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const CREATE_POST_SUCCEED = 'CREATE_POST_SUCCEED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';

export const SINGLE_POST_REQUESTED = 'SINGLE_POST_REQUESTED';
export const SINGLE_POST_SUCCEED = 'SINGLE_POST_SUCCEED';
export const SINGLE_POST_FAILED = 'SINGLE_POST_FAILED';

export const EDIT_POST_REQUESTED = 'EDIT_POST_REQUESTED';
export const EDIT_POST_SUCCEED = 'EDIT_POST_SUCCEED';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';

export const UPDATE_POST_REQUESTED = 'UPDATE_POST_REQUESTED';
export const UPDATE_POST_SUCCEED = 'UPDATE_POST_SUCCEED';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';

export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED';
export const DELETE_POST_SUCCEED = 'DELETE_POST_SUCCEED';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';