export const FETCH_TAG_REQUESTED = 'FETCH_TAG_REQUESTED';
export const FETCH_TAG_SUCCEED = 'FETCH_TAG_SUCCEED';
export const FETCH_TAG_FAILED = 'FETCH_TAG_FAILED';
export const FETCH_TAG_RESETED = 'FETCH_TAG_RESETED';

export const CREATE_TAG_REQUESTED = 'CREATE_TAG_REQUESTED';
export const CREATE_TAG_SUCCEED = 'CREATE_TAG_SUCCEED';
export const CREATE_TAG_FAILED = 'CREATE_TAG_FAILED';
export const CREATE_TAG_RESETED = 'CREATE_TAG_RESETED';

export const SINGLE_TAG_REQUESTED = 'SINGLE_TAG_REQUESTED';
export const SINGLE_TAG_SUCCEED = 'SINGLE_TAG_SUCCEED';
export const SINGLE_TAG_FAILED = 'SINGLE_TAG_FAILED';
export const SINGLE_TAG_RESETED = 'SINGLE_TAG_RESETED';

export const EDIT_TAG_REQUESTED = 'EDIT_TAG_REQUESTED';
export const EDIT_TAG_SUCCEED = 'EDIT_TAG_SUCCEED';
export const EDIT_TAG_FAILED = 'EDIT_TAG_FAILED';
export const EDIT_TAG_RESETED = 'EDIT_TAG_RESETED';

export const UPDATE_TAG_REQUESTED = 'UPDATE_TAG_REQUESTED';
export const UPDATE_TAG_SUCCEED = 'UPDATE_TAG_SUCCEED';
export const UPDATE_TAG_FAILED = 'UPDATE_TAG_FAILED';
export const UPDATE_TAG_RESETED = 'UPDATE_TAG_RESETED';

export const DELETE_TAG_REQUESTED = 'DELETE_TAG_REQUESTED';
export const DELETE_TAG_SUCCEED = 'DELETE_TAG_SUCCEED';
export const DELETE_TAG_FAILED = 'DELETE_TAG_FAILED';
export const DELETE_TAG_RESETED = 'DELETE_TAG_RESETED';
