export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED';
export const FETCH_USER_SUCCEED = 'FETCH_USER_SUCCEED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_RESETED = 'FETCH_USER_RESETED';

export const CREATE_USER_REQUESTED = 'CREATE_USER_REQUESTED';
export const CREATE_USER_SUCCEED = 'CREATE_USER_SUCCEED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const CREATE_USER_RESETED = 'CREATE_USER_RESETED';

export const SINGLE_USER_REQUESTED = 'SINGLE_USER_REQUESTED';
export const SINGLE_USER_SUCCEED = 'SINGLE_USER_SUCCEED';
export const SINGLE_USER_FAILED = 'SINGLE_USER_FAILED';
export const SINGLE_USER_RESETED = 'SINGLE_USER_RESETED';

export const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED';
export const EDIT_USER_SUCCEED = 'EDIT_USER_SUCCEED';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export const EDIT_USER_RESETED = 'EDIT_USER_RESETED';

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED';
export const UPDATE_USER_SUCCEED = 'UPDATE_USER_SUCCEED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_RESETED = 'UPDATE_USER_RESETED';

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCEED = 'DELETE_USER_SUCCEED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const DELETE_USER_RESETED = 'DELETE_USER_RESETED';
