export const FETCH_CATEGORY_REQUESTED = 'FETCH_CATEGORY_REQUESTED';
export const FETCH_CATEGORY_SUCCEED = 'FETCH_CATEGORY_SUCCEED';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FETCH_CATEGORY_RESETED = 'FETCH_CATEGORY_RESETED';

export const CREATE_CATEGORY_REQUESTED = 'CREATE_CATEGORY_REQUESTED';
export const CREATE_CATEGORY_SUCCEED = 'CREATE_CATEGORY_SUCCEED';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';
export const CREATE_CATEGORY_RESETED = 'CREATE_CATEGORY_RESETED';

export const SINGLE_CATEGORY_REQUESTED = 'SINGLE_CATEGORY_REQUESTED';
export const SINGLE_CATEGORY_SUCCEED = 'SINGLE_CATEGORY_SUCCEED';
export const SINGLE_CATEGORY_FAILED = 'SINGLE_CATEGORY_FAILED';
export const SINGLE_CATEGORY_RESETED = 'SINGLE_CATEGORY_RESETED';

export const EDIT_CATEGORY_REQUESTED = 'EDIT_CATEGORY_REQUESTED';
export const EDIT_CATEGORY_SUCCEED = 'EDIT_CATEGORY_SUCCEED';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';
export const EDIT_CATEGORY_RESETED = 'EDIT_CATEGORY_RESETED';

export const UPDATE_CATEGORY_REQUESTED = 'UPDATE_CATEGORY_REQUESTED';
export const UPDATE_CATEGORY_SUCCEED = 'UPDATE_CATEGORY_SUCCEED';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';
export const UPDATE_CATEGORY_RESETED = 'UPDATE_CATEGORY_RESETED';

export const DELETE_CATEGORY_REQUESTED = 'DELETE_CATEGORY_REQUESTED';
export const DELETE_CATEGORY_SUCCEED = 'DELETE_CATEGORY_SUCCEED';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const DELETE_CATEGORY_RESETED = 'DELETE_CATEGORY_RESETED';
